$pdf_mode = 5;          # 5 = xelatex
$pdflatex = 'xelatex %O %S';
$bibtex_use = 2;
$biber = 'biber %O %S';
$xelatex = 'xelatex -interaction=nonstopmode -synctex=1 %O %S';
$pdf_previewer = 'xdg-open';
@default_files = ('main.tex');
$out_dir = '_build';
