# ===============================================================
# 抽取自仓库 [current]: examples/deuteron_proton_Ay.py
# 行号区段：89..142
# 由 docs/treatise/code_excerpts/extract.py 自动生成；勿手动编辑
# ===============================================================
def write_solver_inputs(cfg: SolverRunConfig) -> tuple[Path, Path, Path, Path]:
    cpp_input_dir = cfg.root / "CPP" / "Input"
    cpp_input_dir.mkdir(parents=True, exist_ok=True)

    solver_out_dir = cfg.work_dir / "solver_out"
    p123_dir = cfg.work_dir / "p123"
    solver_out_dir.mkdir(parents=True, exist_ok=True)
    p123_dir.mkdir(parents=True, exist_ok=True)

    tlab_label = format_tlab_label(cfg.target_tlab_mev)
    energy_file = cpp_input_dir / f"tlab_{tlab_label}_validation_autogen.txt"
    energy_file.write_text(f"{cfg.target_tlab_mev:.6f}\n", encoding="utf-8")

    config_file = cpp_input_dir / f"input_tlab_{tlab_label}_solver_validation_autogen.txt"
    config_file.write_text(
        "\n".join(
            [
                f"# Autogenerated solver validation config for target Tlab = {cfg.target_tlab_mev:.6f} MeV",
                f"two_J_3N_max={cfg.two_j_3n_max}",
                f"J_2N_max={cfg.j_2n_max}",
                f"Np_WP={cfg.np_wp}",
                f"Nq_WP={cfg.nq_wp}",
                f"Nphi={cfg.nphi}",
                f"Nx={cfg.nx}",
                f"Np_per_WP={cfg.np_per_wp}",
                f"Nq_per_WP={cfg.nq_per_wp}",
                f"chebyshev_s={cfg.chebyshev_s}",
                f"chebyshev_t={cfg.chebyshev_t}",
                "p_grid_type=chebyshev",
                "q_grid_type=chebyshev",
                f"P123_omp_num_threads={cfg.threads}",
                "parallel_run=false",
                "P123_recovery=false",
                "tensor_force=true",
                "isospin_breaking_1S0=true",
                "midpoint_approx=false",
                f"calculate_and_store_P123={'true' if cfg.calculate_p123 else 'false'}",
                "include_breakup_channels=false",
                "solve_faddeev=true",
                "solve_dense=false",
                "production_run=true",
                f"potential_model={cfg.potential_model}",
                "parameter_walk=false",
                "parameter_file=",
                "PSI_start=-1",
                "PSI_end=-1",
                f"energy_input_file={_rel_to_cpp(energy_file, cfg.root)}",
                f"output_folder={_rel_to_cpp(solver_out_dir, cfg.root)}",
                f"P123_folder={_rel_to_cpp(p123_dir, cfg.root)}",
                "",
            ]
        ),
        encoding="utf-8",
    )
