#include "chiral_N2LO_3NF_full_reference.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <string>

namespace {

int failures = 0;

void expect_close(const char* label, double value, double expected,
                  double relative_tolerance = 3.0e-12,
                  double absolute_tolerance = 3.0e-13)
{
	const double error = std::abs(value - expected);
	const double tolerance = absolute_tolerance
	                       + relative_tolerance * std::max(std::abs(value), std::abs(expected));
	if (error > tolerance) {
		std::printf("FAIL %-30s got=% .17e expected=% .17e error=%.3e tolerance=%.3e\n",
		            label, value, expected, error, tolerance);
		++failures;
	} else {
		std::printf("PASS %-30s value=% .17e\n", label, value);
	}
}

void expect_true(const char* label, bool condition)
{
	if (!condition) {
		std::printf("FAIL %s\n", label);
		++failures;
	} else {
		std::printf("PASS %s\n", label);
	}
}

struct five_channel_space {
	int l_pair[5] = {1, 0, 0, 1, 0};
	int s_pair[5] = {1, 1, 0, 1, 0};
	int j_pair[5] = {1, 1, 0, 2, 0};
	int t_pair[5] = {1, 0, 1, 1, 1};
	int lambda[5] = {1, 0, 0, 0, 1};
	int two_i[5] = {1, 1, 1, 1, 3};
	int two_j[5] = {1, 1, 1, 3, 3};
	int two_t[5] = {1, 1, 1, 1, 3};
	int parity[5] = {1, 1, 1, -1, -1};
	pw_3N_statespace pw{};

	five_channel_space()
	{
		pw.Nalpha = 5;
		pw.L_2N_array = l_pair;
		pw.S_2N_array = s_pair;
		pw.J_2N_array = j_pair;
		pw.T_2N_array = t_pair;
		pw.L_1N_array = lambda;
		pw.two_J_1N_array = two_i;
		pw.two_J_3N_array = two_j;
		pw.two_T_3N_array = two_t;
		pw.P_3N_array = parity;
	}
};

} // namespace

int main()
{
	five_channel_space space;
	constexpr double p_bra = 0.9;
	constexpr double q_bra = 1.1;
	constexpr double p_ket = 0.4;
	constexpr double q_ket = 0.7;

	// Values were generated by the independent Python direct-Jj projector at
	// order N=2, including the Lambda=500 MeV regulator and Tic-tac (2pi)^-6.
	chiral_N2LO_3NF_full_reference all(
		-0.2, -0.205, 500.0, -0.81, -3.2, 5.4, 2);
	expect_close("P-wave diagonal all terms",
		all.W1_element(0, 0, p_bra, q_bra, p_ket, q_ket, space.pw),
		7.158430968979254e-4);
	expect_close("S-wave off-diagonal all terms",
		all.W1_element(1, 2, p_bra, q_bra, p_ket, q_ket, space.pw),
		1.0910816762919285e-2);
	expect_close("S-wave diagonal all terms",
		all.W1_element(1, 1, p_bra, q_bra, p_ket, q_ket, space.pw),
		1.3967392063131844e-2);

	chiral_N2LO_3NF_full_reference c1(
		0.0, 0.0, 500.0, -0.81, 0.0, 0.0, 2);
	chiral_N2LO_3NF_full_reference c3(
		0.0, 0.0, 500.0, 0.0, -3.2, 0.0, 2);
	chiral_N2LO_3NF_full_reference c4(
		0.0, 0.0, 500.0, 0.0, 0.0, 5.4, 2);
	chiral_N2LO_3NF_full_reference cD(
		-0.2, 0.0, 500.0, 0.0, 0.0, 0.0, 2);
	chiral_N2LO_3NF_full_reference cE(
		0.0, -0.205, 500.0, 0.0, 0.0, 0.0, 2);
	expect_close("P-wave c1 component",
		c1.W1_element(0, 0, p_bra, q_bra, p_ket, q_ket, space.pw),
		7.4522364848492146e-5);
	expect_close("P-wave c3 component",
		c3.W1_element(0, 0, p_bra, q_bra, p_ket, q_ket, space.pw),
		6.4132073204943335e-4);
	expect_close("S-wave c4 transition",
		c4.W1_element(1, 2, p_bra, q_bra, p_ket, q_ket, space.pw),
		1.0251228601276630e-2);
	expect_close("S-wave cD transition",
		cD.W1_element(1, 2, p_bra, q_bra, p_ket, q_ket, space.pw),
		6.5958816164265555e-4);
	expect_close("S-wave cE diagonal",
		cE.W1_element(1, 1, p_bra, q_bra, p_ket, q_ket, space.pw),
		8.6321225934281043e-3);
	expect_close("J=3/2 negative-parity c1",
		c1.W1_element(3, 3, p_bra, q_bra, p_ket, q_ket, space.pw),
		-6.457082273497459e-5);
	expect_close("J=3/2 negative-parity c3",
		c3.W1_element(3, 3, p_bra, q_bra, p_ket, q_ket, space.pw),
		6.399148469714615e-5);
	expect_close("T=3/2 negative-parity all",
		all.W1_element(4, 4, p_bra, q_bra, p_ket, q_ket, space.pw),
		1.0059428880282043e-3);

	const double forward = all.W1_element(
		1, 2, p_bra, q_bra, p_ket, q_ket, space.pw);
	const double reverse = all.W1_element(
		2, 1, p_ket, q_ket, p_bra, q_bra, space.pw);
	// At N=2 the two fixed-axis representations are not angularly converged and
	// are therefore not yet equal.  Freeze the independent oracle's reverse
	// value instead of hiding the quadrature error by post-hoc symmetrisation;
	// Hermiticity is a separate N-angle convergence gate.
	expect_close("reverse low-order oracle", reverse, 1.3545068698023570e-2);
	expect_close("forward low-order oracle", forward, 1.0910816762919285e-2);
	const double contact_forward = cE.W1_element(
		1, 1, p_bra, q_bra, p_ket, q_ket, space.pw);
	const double contact_reverse = cE.W1_element(
		1, 1, p_ket, q_ket, p_bra, q_bra, space.pw);
	expect_close("contact Hermitian exactly", contact_reverse, contact_forward);

	// Fixed-axis forward/reverse differences must shrink with angular order.
	// The signed N=4 and N=6 values are independently frozen from Python.
	chiral_N2LO_3NF_full_reference all4(
		-0.2, -0.205, 500.0, -0.81, -3.2, 5.4, 4);
	const double forward4 = all4.W1_element(
		1, 2, p_bra, q_bra, p_ket, q_ket, space.pw);
	const double reverse4 = all4.W1_element(
		2, 1, p_ket, q_ket, p_bra, q_bra, space.pw);
	expect_close("forward Nangle=4 oracle", forward4, 1.3808781771934725e-2);
	expect_close("reverse Nangle=4 oracle", reverse4, 1.3881881139728283e-2);

	chiral_N2LO_3NF_full_reference all6(
		-0.2, -0.205, 500.0, -0.81, -3.2, 5.4, 6);
	const double forward6 = all6.W1_element(
		1, 2, p_bra, q_bra, p_ket, q_ket, space.pw);
	const double reverse6 = all6.W1_element(
		2, 1, p_ket, q_ket, p_bra, q_bra, space.pw);
	expect_close("forward Nangle=6 oracle", forward6, 1.3775796815388002e-2);
	expect_close("reverse Nangle=6 oracle", reverse6, 1.3784579177913635e-2);
	expect_true("Hermiticity residual decreases N=2->4",
		std::abs(forward4 - reverse4) < std::abs(forward - reverse));
	expect_true("Hermiticity residual decreases N=4->6",
		std::abs(forward6 - reverse6) < std::abs(forward4 - reverse4));

	chiral_N2LO_3NF_full_reference zero(
		0.0, 0.0, 500.0, 0.0, 0.0, 0.0, 2);
	expect_close("all LECs zero",
		zero.W1_element(1, 1, p_bra, q_bra, p_ket, q_ket, space.pw), 0.0);

	if (failures != 0) {
		std::printf("%d complete-reference tests failed\n", failures);
		return 1;
	}
	std::printf("All complete N2LO five-angle C++ reference tests passed.\n");
	return 0;
}
