#!/usr/bin/env python3
"""
Purpose:
  Run Tic-tac solver for a single target Tlab value in MeV.

What this script does:
  1) Build autogenerated solver input files under `CPP/Input/`.
  2) Run solver binary (`CPP/run` by default).
  3) Write artifacts to `<work-dir>/solver_out` and `<work-dir>/p123`.
  4) Validate that U_PW_elements files contain parseable numeric rows.

Data flow (left -> right):
  CLI args
    -> autogenerated solver config + energy file
    -> solver run
    -> solver_out/U_PW_elements_*.txt + solver_run.log

Calls / dependencies:
  - Calls `make -C CPP -j` when solver binary is missing.
  - Calls `CPP/run` with autogenerated config file.

Usage:
  python3 examples/deuteron_proton_Ay.py \
    --work-dir output/deuteron_proton_Ay \
    --target-tlab-mev 190 \
    --reuse-p123
"""

from __future__ import annotations

import argparse
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import List

from tlab_utils import format_tlab_label


@dataclass
class SolverRunConfig:
    root: Path
    work_dir: Path
    solver: Path
    target_tlab_mev: float
    two_j_3n_max: int
    j_2n_max: int
    np_wp: int
    nq_wp: int
    nphi: int
    nx: int
    np_per_wp: int
    nq_per_wp: int
    chebyshev_s: float
    chebyshev_t: float
    threads: int
    potential_model: str
    timeout_s: int
    calculate_p123: bool


def _rel_to_cpp(path: Path, root: Path) -> str:
    cpp_dir = root / "CPP"
    return os.path.relpath(path.resolve(), cpp_dir.resolve())


def ensure_cpp_solver_binary(root: Path, solver_path: Path) -> None:
    if solver_path.exists():
        return

    if solver_path != root / "CPP" / "run":
        raise FileNotFoundError(f"Solver binary not found: {solver_path}")

    result = subprocess.run(
        ["make", "-C", str(root / "CPP"), "-j"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "Failed to build CPP/run using `make -C CPP`.\n"
            f"stdout:\n{result.stdout}\n"
            f"stderr:\n{result.stderr}"
        )


def write_solver_inputs(cfg: SolverRunConfig) -> tuple[Path, Path, Path, Path]:
    cpp_input_dir = cfg.root / "CPP" / "Input"
    cpp_input_dir.mkdir(parents=True, exist_ok=True)

    solver_out_dir = cfg.work_dir / "solver_out"
    p123_dir = cfg.work_dir / "p123"
    solver_out_dir.mkdir(parents=True, exist_ok=True)
    p123_dir.mkdir(parents=True, exist_ok=True)

    tlab_label = format_tlab_label(cfg.target_tlab_mev)
    energy_file = cpp_input_dir / f"tlab_{tlab_label}_validation_autogen.txt"
    energy_file.write_text(f"{cfg.target_tlab_mev:.6f}\n", encoding="utf-8")

    config_file = cpp_input_dir / f"input_tlab_{tlab_label}_solver_validation_autogen.txt"
    config_file.write_text(
        "\n".join(
            [
                f"# Autogenerated solver validation config for target Tlab = {cfg.target_tlab_mev:.6f} MeV",
                f"two_J_3N_max={cfg.two_j_3n_max}",
                f"J_2N_max={cfg.j_2n_max}",
                f"Np_WP={cfg.np_wp}",
                f"Nq_WP={cfg.nq_wp}",
                f"Nphi={cfg.nphi}",
                f"Nx={cfg.nx}",
                f"Np_per_WP={cfg.np_per_wp}",
                f"Nq_per_WP={cfg.nq_per_wp}",
                f"chebyshev_s={cfg.chebyshev_s}",
                f"chebyshev_t={cfg.chebyshev_t}",
                "p_grid_type=chebyshev",
                "q_grid_type=chebyshev",
                f"P123_omp_num_threads={cfg.threads}",
                "parallel_run=false",
                "P123_recovery=false",
                "tensor_force=true",
                "isospin_breaking_1S0=true",
                "midpoint_approx=false",
                f"calculate_and_store_P123={'true' if cfg.calculate_p123 else 'false'}",
                "include_breakup_channels=false",
                "solve_faddeev=true",
                "solve_dense=false",
                "production_run=true",
                f"potential_model={cfg.potential_model}",
                "parameter_walk=false",
                "parameter_file=",
                "PSI_start=-1",
                "PSI_end=-1",
                f"energy_input_file={_rel_to_cpp(energy_file, cfg.root)}",
                f"output_folder={_rel_to_cpp(solver_out_dir, cfg.root)}",
                f"P123_folder={_rel_to_cpp(p123_dir, cfg.root)}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    log_file = cfg.work_dir / "solver_run.log"
    return energy_file, config_file, solver_out_dir, log_file


def run_cpp_solver(cfg: SolverRunConfig) -> dict:
    ensure_cpp_solver_binary(cfg.root, cfg.solver)
    energy_file, config_file, solver_out_dir, log_file = write_solver_inputs(cfg)

    cpp_cwd = cfg.root / "CPP"
    solver_rel = os.path.relpath(cfg.solver.resolve(), cpp_cwd.resolve())
    if not solver_rel.startswith("."):
        solver_rel = f"./{solver_rel}"
    config_rel = os.path.relpath(config_file.resolve(), cpp_cwd.resolve())

    cmd = [solver_rel, config_rel]
    env = os.environ.copy()
    env["HDF5_DISABLE_VERSION_CHECK"] = "2"

    with log_file.open("w", encoding="utf-8") as log_handle:
        result = subprocess.run(
            cmd,
            cwd=cpp_cwd,
            env=env,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=cfg.timeout_s,
        )

    u_files = sorted(solver_out_dir.glob("U_PW_elements_*.txt"))
    has_u_data = False
    for u_file in u_files:
        for raw_line in u_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 7:
                continue
            try:
                float(parts[0])
                float(parts[1])
                int(parts[2])
                complex(parts[3])
                has_u_data = True
                break
            except Exception:
                continue
        if has_u_data:
            break

    return {
        "returncode": result.returncode,
        "log_file": log_file,
        "energy_file": energy_file,
        "config_file": config_file,
        "solver_out_dir": solver_out_dir,
        "u_files": u_files,
        "has_u_data": has_u_data,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run Tic-tac solver for a target Tlab value in MeV")
    parser.add_argument("--work-dir", default="output/deuteron_proton_Ay", help="Work/output directory")
    parser.add_argument("--solver", default="CPP/run", help="Solver binary path (default: CPP/run)")
    parser.add_argument("--target-tlab-mev", type=float, default=190.0, help="Target Tlab value in MeV")
    parser.add_argument("--two-j-3n-max", type=int, default=1)
    parser.add_argument("--j-2n-max", type=int, default=2)
    parser.add_argument("--np", type=int, default=20)
    parser.add_argument("--nq", type=int, default=20)
    parser.add_argument("--nphi", type=int, default=24)
    parser.add_argument("--nx", type=int, default=24)
    parser.add_argument("--np-per-wp", type=int, default=6)
    parser.add_argument("--nq-per-wp", type=int, default=6)
    parser.add_argument("--chebyshev-s", type=float, default=150.0)
    parser.add_argument("--chebyshev-t", type=float, default=1.0)
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--potential-model", default="LO_internal")
    parser.add_argument("--timeout", type=int, default=1800, help="Solver timeout in seconds")
    parser.add_argument(
        "--reuse-p123",
        action="store_true",
        help="Reuse existing P123 files (sets calculate_and_store_P123=false)",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    root = Path(__file__).resolve().parents[1]

    # Build a single immutable config object that carries all run parameters.
    cfg = SolverRunConfig(
        root=root,
        work_dir=(root / args.work_dir).resolve(),
        solver=(root / args.solver).resolve() if not Path(args.solver).is_absolute() else Path(args.solver),
        target_tlab_mev=args.target_tlab_mev,
        two_j_3n_max=args.two_j_3n_max,
        j_2n_max=args.j_2n_max,
        np_wp=args.np,
        nq_wp=args.nq,
        nphi=args.nphi,
        nx=args.nx,
        np_per_wp=args.np_per_wp,
        nq_per_wp=args.nq_per_wp,
        chebyshev_s=args.chebyshev_s,
        chebyshev_t=args.chebyshev_t,
        threads=args.threads,
        potential_model=args.potential_model,
        timeout_s=args.timeout,
        calculate_p123=(not args.reuse_p123),
    )

    # Execute solver and summarize where outputs landed.
    result = run_cpp_solver(cfg)

    print("Tic-tac solver run finished")
    print(f"return code:   {result['returncode']}")
    print(f"config file:   {result['config_file']}")
    print(f"energy file:   {result['energy_file']}")
    print(f"solver output: {result['solver_out_dir']}")
    print(f"solver log:    {result['log_file']}")
    print(f"U-files found: {len(result['u_files'])}")
    print(f"U data rows:   {'yes' if result['has_u_data'] else 'no'}")

    if result["returncode"] != 0:
        return 2
    if not result["u_files"] or not result["has_u_data"]:
        return 3
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
